apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-demo-page
  namespace: devops-course
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>GitOps DevOps Final</title>
    </head>
    <body>
      <h1>GitOps con Argo CD en K3s</h1>
      <p>Aplicacion desplegada desde Git usando Argo CD.</p>
      <p>Version: v1</p>
      <p>Provando Cambio</p>
    </body>
    </html>