apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-app
  namespace: devops-course
  labels:
    app: devops-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo-app
  template:
    metadata:
      labels:
        app: devops-demo-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: html
          configMap:
            name: devops-demo-page