apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-app
  namespace: devops-course
  labels:
    app: devops-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo-app
  template:
    metadata:
      labels:
        app: devops-demo-app
    spec:
      containers:
        - name: gitops-sentiment-demo
          image: ghcr.io/renzoal7/gitops-sentiment-demo:main-3d19e87
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: APP_MODE
              value: PRODUCTION
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
